// Code generated by ogen, DO NOT EDIT.

package frankfurterclient

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetRates implements getRates operation.
//
// Returns exchange rates blended across providers. Without date params, returns the latest rates. Each
// record is a single currency pair. The response includes an identity record for the base currency
// (base equals quote, rate 1), subject to the quotes filter like any other record. Daily date ranges
// of any length are served, including full history. Limit: requests using `providers` or
// `expand=providers` recompute the blend per date, so at daily granularity they return 422 for ranges
// longer than 5 years. A single provider is exempt and serves any range. With `providers` naming 2 to
// 5 providers, a `quotes` list of at most 5 currencies lifts the cap; without `providers`,
// `expand=providers` ranges compute every currency regardless of `quotes`, so aggregate with
// `group=week` or `group=month`, add `providers`, or split the range into shorter requests.
//
// GET /rates
func (UnimplementedHandler) GetRates(ctx context.Context, params GetRatesParams) (r GetRatesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrRespStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrRespStatusCode) {
	r = new(ErrRespStatusCode)
	return r
}
