// Code generated by ogen, DO NOT EDIT.

package frankfurterclient

import (
	"fmt"
	"io"
	"time"

	"github.com/go-faster/errors"
)

func (s *ErrRespStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// ErrRespStatusCode wraps string with StatusCode.
type ErrRespStatusCode struct {
	StatusCode int
	Response   string
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrRespStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrRespStatusCode) GetResponse() string {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrRespStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrRespStatusCode) SetResponse(val string) {
	s.Response = val
}

type Expand string

const (
	ExpandProviders Expand = "providers"
)

// AllValues returns all Expand values.
func (Expand) AllValues() []Expand {
	return []Expand{
		ExpandProviders,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Expand) MarshalText() ([]byte, error) {
	switch s {
	case ExpandProviders:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Expand) UnmarshalText(data []byte) error {
	switch Expand(data) {
	case ExpandProviders:
		*s = ExpandProviders
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type GetRatesOKApplicationJSON []Rate

func (*GetRatesOKApplicationJSON) getRatesRes() {}

// NDJSON stream of Rate objects, one JSON object per line.
type GetRatesOKApplicationXNdjson struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetRatesOKApplicationXNdjson) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetRatesOKApplicationXNdjson) getRatesRes() {}

type Group string

const (
	GroupWeek  Group = "week"
	GroupMonth Group = "month"
)

// AllValues returns all Group values.
func (Group) AllValues() []Group {
	return []Group{
		GroupWeek,
		GroupMonth,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Group) MarshalText() ([]byte, error) {
	switch s {
	case GroupWeek:
		return []byte(s), nil
	case GroupMonth:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Group) UnmarshalText(data []byte) error {
	switch Group(data) {
	case GroupWeek:
		*s = GroupWeek
		return nil
	case GroupMonth:
		*s = GroupMonth
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type NotFound struct {
	Message OptString `json:"message"`
}

// GetMessage returns the value of Message.
func (s *NotFound) GetMessage() OptString {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *NotFound) SetMessage(val OptString) {
	s.Message = val
}

func (*NotFound) getRatesRes() {}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDate returns new OptDate with value set to v.
func NewOptDate(v time.Time) OptDate {
	return OptDate{
		Value: v,
		Set:   true,
	}
}

// OptDate is optional time.Time.
type OptDate struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDate was set.
func (o OptDate) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDate) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDate) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDate) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDate) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptExpand returns new OptExpand with value set to v.
func NewOptExpand(v Expand) OptExpand {
	return OptExpand{
		Value: v,
		Set:   true,
	}
}

// OptExpand is optional Expand.
type OptExpand struct {
	Value Expand
	Set   bool
}

// IsSet returns true if OptExpand was set.
func (o OptExpand) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptExpand) Reset() {
	var v Expand
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptExpand) SetTo(v Expand) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptExpand) Get() (v Expand, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptExpand) Or(d Expand) Expand {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptGroup returns new OptGroup with value set to v.
func NewOptGroup(v Group) OptGroup {
	return OptGroup{
		Value: v,
		Set:   true,
	}
}

// OptGroup is optional Group.
type OptGroup struct {
	Value Group
	Set   bool
}

// IsSet returns true if OptGroup was set.
func (o OptGroup) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptGroup) Reset() {
	var v Group
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptGroup) SetTo(v Group) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptGroup) Get() (v Group, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptGroup) Or(d Group) Group {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Rate
type Rate struct {
	// The date of the rate.
	Date time.Time `json:"date"`
	// Base currency or accounting unit code.
	Base string `json:"base"`
	// Quote currency or accounting unit code.
	Quote string `json:"quote"`
	// Exchange rate value.
	Rate float64 `json:"rate"`
	// Per-provider rates for this pair. Present only when `expand=providers` is set. Each entry has the
	// provider's observation date and published rate (rebased to the row's base). Entries with
	// `excluded: true` did not contribute to the blended `rate` — either flagged as outliers by the
	// consensus filter, or overridden by a currency peg. Omitted on synthesized peg rows where no provider
	// published the quote.
	Providers []RateProvidersItem `json:"providers"`
}

// GetDate returns the value of Date.
func (s *Rate) GetDate() time.Time {
	return s.Date
}

// GetBase returns the value of Base.
func (s *Rate) GetBase() string {
	return s.Base
}

// GetQuote returns the value of Quote.
func (s *Rate) GetQuote() string {
	return s.Quote
}

// GetRate returns the value of Rate.
func (s *Rate) GetRate() float64 {
	return s.Rate
}

// GetProviders returns the value of Providers.
func (s *Rate) GetProviders() []RateProvidersItem {
	return s.Providers
}

// SetDate sets the value of Date.
func (s *Rate) SetDate(val time.Time) {
	s.Date = val
}

// SetBase sets the value of Base.
func (s *Rate) SetBase(val string) {
	s.Base = val
}

// SetQuote sets the value of Quote.
func (s *Rate) SetQuote(val string) {
	s.Quote = val
}

// SetRate sets the value of Rate.
func (s *Rate) SetRate(val float64) {
	s.Rate = val
}

// SetProviders sets the value of Providers.
func (s *Rate) SetProviders(val []RateProvidersItem) {
	s.Providers = val
}

type RateProvidersItem struct {
	// Provider key.
	Key string `json:"key"`
	// Provider observation date used for this entry.
	Date time.Time `json:"date"`
	// Provider's rate, rebased to the row's base.
	Rate float64 `json:"rate"`
	// Present and true when this entry did not contribute to the blended rate.
	Excluded OptBool `json:"excluded"`
}

// GetKey returns the value of Key.
func (s *RateProvidersItem) GetKey() string {
	return s.Key
}

// GetDate returns the value of Date.
func (s *RateProvidersItem) GetDate() time.Time {
	return s.Date
}

// GetRate returns the value of Rate.
func (s *RateProvidersItem) GetRate() float64 {
	return s.Rate
}

// GetExcluded returns the value of Excluded.
func (s *RateProvidersItem) GetExcluded() OptBool {
	return s.Excluded
}

// SetKey sets the value of Key.
func (s *RateProvidersItem) SetKey(val string) {
	s.Key = val
}

// SetDate sets the value of Date.
func (s *RateProvidersItem) SetDate(val time.Time) {
	s.Date = val
}

// SetRate sets the value of Rate.
func (s *RateProvidersItem) SetRate(val float64) {
	s.Rate = val
}

// SetExcluded sets the value of Excluded.
func (s *RateProvidersItem) SetExcluded(val OptBool) {
	s.Excluded = val
}

type ServiceUnavailable struct {
	Message OptString `json:"message"`
}

// GetMessage returns the value of Message.
func (s *ServiceUnavailable) GetMessage() OptString {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *ServiceUnavailable) SetMessage(val OptString) {
	s.Message = val
}

// ServiceUnavailableHeaders wraps ServiceUnavailable with response headers.
type ServiceUnavailableHeaders struct {
	RetryAfter OptInt
	Response   ServiceUnavailable
}

// GetRetryAfter returns the value of RetryAfter.
func (s *ServiceUnavailableHeaders) GetRetryAfter() OptInt {
	return s.RetryAfter
}

// GetResponse returns the value of Response.
func (s *ServiceUnavailableHeaders) GetResponse() ServiceUnavailable {
	return s.Response
}

// SetRetryAfter sets the value of RetryAfter.
func (s *ServiceUnavailableHeaders) SetRetryAfter(val OptInt) {
	s.RetryAfter = val
}

// SetResponse sets the value of Response.
func (s *ServiceUnavailableHeaders) SetResponse(val ServiceUnavailable) {
	s.Response = val
}

func (*ServiceUnavailableHeaders) getRatesRes() {}

type UnprocessableEntity struct {
	Message OptString `json:"message"`
}

// GetMessage returns the value of Message.
func (s *UnprocessableEntity) GetMessage() OptString {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *UnprocessableEntity) SetMessage(val OptString) {
	s.Message = val
}

func (*UnprocessableEntity) getRatesRes() {}
