// Code generated by ogen, DO NOT EDIT.

package frankfurterclient

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetRates implements getRates operation.
	//
	// Returns exchange rates blended across providers. Without date params, returns the latest rates. Each
	// record is a single currency pair. The response includes an identity record for the base currency
	// (base equals quote, rate 1), subject to the quotes filter like any other record. Daily date ranges
	// of any length are served, including full history. Limit: requests using `providers` or
	// `expand=providers` recompute the blend per date, so at daily granularity they return 422 for ranges
	// longer than 5 years. A single provider is exempt and serves any range. With `providers` naming 2 to
	// 5 providers, a `quotes` list of at most 5 currencies lifts the cap; without `providers`,
	// `expand=providers` ranges compute every currency regardless of `quotes`, so aggregate with
	// `group=week` or `group=month`, add `providers`, or split the range into shorter requests.
	//
	// GET /rates
	GetRates(ctx context.Context, params GetRatesParams) (GetRatesRes, error)
	// NewError creates *ErrRespStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrRespStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
