// Code generated by ogen, DO NOT EDIT.

package frankfurterclient

import (
	"net/http"
	"time"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// GetRatesParams is parameters of getRates operation.
type GetRatesParams struct {
	// Specific date (YYYY-MM-DD). Cannot be combined with from/to.
	Date OptDate `json:",omitempty,omitzero"`
	// Start of date range (YYYY-MM-DD).
	From OptDate `json:",omitempty,omitzero"`
	// End of date range (YYYY-MM-DD). Defaults to today.
	To OptDate `json:",omitempty,omitzero"`
	// Base currency (default: EUR).
	Base OptString `json:",omitempty,omitzero"`
	// Comma-separated list of quote currencies to include.
	Quotes OptString `json:",omitempty,omitzero"`
	// Comma-separated list of data providers to include. A single provider includes its stored
	// non-currency series. Selecting multiple providers blends only registered currencies and accounting
	// units.
	Providers OptString `json:",omitempty,omitzero"`
	// Downsample rates by time period. Only applies to date ranges.
	Group OptGroup `json:",omitempty,omitzero"`
	// Comma-separated list of optional fields to include per record. Currently supports `providers`, which
	// adds an array of `{ key, date, rate }` objects per record showing each provider's individual
	// observation date and rate. Outliers excluded from the blend (and providers whose rate was overridden
	// by a currency peg) are flagged with `excluded: true`. The field is omitted on synthesized peg rows
	// where no provider published the quote. In CSV output, the `providers` column is encoded as
	// `KEY:RATE` pairs joined by `|`, with a trailing `*` on excluded entries (e.g. `ECB:0.92|FED:1.50*`).
	Expand OptExpand `json:",omitempty,omitzero"`
}

func unpackGetRatesParams(packed middleware.Parameters) (params GetRatesParams) {
	{
		key := middleware.ParameterKey{
			Name: "date",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Date = v.(OptDate)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "from",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.From = v.(OptDate)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "to",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.To = v.(OptDate)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "base",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Base = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "quotes",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Quotes = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "providers",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Providers = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "group",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Group = v.(OptGroup)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "expand",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Expand = v.(OptExpand)
		}
	}
	return params
}

func decodeGetRatesParams(args [0]string, argsEscaped bool, r *http.Request) (params GetRatesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: date.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "date",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDateVal time.Time
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToDate(val)
					if err != nil {
						return err
					}

					paramsDotDateVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Date.SetTo(paramsDotDateVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "date",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: from.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "from",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotFromVal time.Time
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToDate(val)
					if err != nil {
						return err
					}

					paramsDotFromVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.From.SetTo(paramsDotFromVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "from",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: to.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "to",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotToVal time.Time
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToDate(val)
					if err != nil {
						return err
					}

					paramsDotToVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.To.SetTo(paramsDotToVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "to",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: base.
	{
		val := string("EUR")
		params.Base.SetTo(val)
	}
	// Decode query: base.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "base",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotBaseVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotBaseVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Base.SetTo(paramsDotBaseVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "base",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: quotes.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "quotes",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotQuotesVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotQuotesVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Quotes.SetTo(paramsDotQuotesVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "quotes",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: providers.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "providers",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotProvidersVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotProvidersVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Providers.SetTo(paramsDotProvidersVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "providers",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: group.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "group",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotGroupVal Group
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotGroupVal = Group(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Group.SetTo(paramsDotGroupVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Group.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "group",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: expand.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "expand",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotExpandVal Expand
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotExpandVal = Expand(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Expand.SetTo(paramsDotExpandVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Expand.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "expand",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
